// scripts/addIndustryLabels.js
import fs from "fs";
import path from "path";
import industries from "../app/lib/_industryList25.js";

const toTitleCase = (str) =>
  str
    .replace(/-/g, " ")
    .replace(/\b\w/g, (l) => l.toUpperCase());

const updated = industries.map((i) => {
  if (i.label && typeof i.label === "string") {
    return i;
  }

  const label =
    i.h1 ||
    i.shortLabel ||
    toTitleCase(i.slug || "");

  return {
    ...i,
    label,
  };
});

const outPath = path.resolve(
  "app/lib/_industryList25.js"
);

const fileContents = `// AUTO-GENERATED — DO NOT EDIT BY HAND
// Generated by scripts/addIndustryLabels.js

export default ${JSON.stringify(updated, null, 2)};
`;

fs.writeFileSync(outPath, fileContents, "utf8");

console.log("✅ Industry labels added successfully");
console.log(`→ Updated ${updated.length} industries`);