/**
 * Auto-refactor industry config
 * - label → audience
 * - infer industry from title
 *
 * SAFE:
 * - Does not mutate source file
 * - Writes a new output file
 */

import fs from "fs";
import path from "path";
import vm from "vm";

const SOURCE_FILE = path.resolve("app/lib/_industryList25.js");
const OUTPUT_FILE = path.resolve("app/lib/_industryList25.refactored.js");

/**
 * Extract "Industry" from titles like:
 * "Roofing Business Loans" → "Roofing"
 */
function inferIndustry(title = "") {
  return title
    .replace(/Business Loans?/i, "")
    .replace(/Loans?/i, "")
    .trim();
}

// Read source
const sourceCode = fs.readFileSync(SOURCE_FILE, "utf-8");

// Wrap module to safely return industries
const wrapped = `
(() => {
  ${sourceCode.replace(/export default\s+industries\s*;?/, "")}
  return industries;
})()
`;

const sandbox = {};
const industries = vm.runInNewContext(wrapped, sandbox);

if (!Array.isArray(industries)) {
  throw new Error("Failed to load industries array");
}

// Transform
const refactored = industries.map((industry) => {
  const { label, ...rest } = industry;

  return {
    ...rest,
    industry: inferIndustry(industry.title),
    audience: label
  };
});

// Write output
const output = `// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Generated by scripts/refactorIndustries.js

const industries = ${JSON.stringify(refactored, null, 2)};

export default industries;
`;

fs.writeFileSync(OUTPUT_FILE, output, "utf-8");

console.log("✅ Refactor complete!");
console.log("→", OUTPUT_FILE);